[package]
name = "homehub-server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
homehub-db = { path = "../homehub-db" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7.4" }
