//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::app_user::Entity as AppUser;
pub use super::light::Entity as Light;
pub use super::location::Entity as Location;
pub use super::room::Entity as Room;
pub use super::room_light::Entity as RoomLight;
